# Generated by Django 4.2.17 on 2024-12-24 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recording',
            new_name='Speech',
        ),
    ]
